Replaced "en orden de" with "Para poder"
DjangoGirls/tutorial-extensions pull request #134
Opened 2019-10-04 15:33 UTC by pcp16

"En orden de" sounds awkward in Spanish, seems like a literal translation of "In order to". Changed to "para poder".

2019-10-04 15:48 UTC, pcp16 commented
Added another commit with some typos corrected.

2019-10-04 15:52 UTC, pcp16 commented
Hope I'm doing this right ...

2019-10-04 21:07 UTC, das-g commented
@DjangoGirls/es-pr please review.

2019-11-13 15:05 UTC, das-g commented
ping @DjangoGirls/es-pr

2023-06-01 12:58 UTC, adRn-s requested changes
Other than the mentioned typo, this looks good to merge!

2023-06-01 12:58 UTC, adRn-s commented on es/domain/README.md
> +* Escrine el nombre de tu dominio
`s/Escrine/Escribe/`

2024-09-21 08:20 UTC, das-g commented on es/domain/README.md
> +* Escrine el nombre de tu dominio
Thus
```suggestion
* Escribe el nombre de tu dominio
```

2024-09-21 08:22 UTC, merged

2024-09-21 08:23 UTC, das-g commented
Thank you, @pcp16 and @adRn-s, and sorry for the long wait.